// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

using System;

namespace Roslynator.Formatting.CSharp
{
    public static partial class DiagnosticIdentifiers
    {
        [Obsolete("", error: true)]
        public const string RemoveEmptyLineBetweenSingleLineAccessors2 = "RCS0035";
        [Obsolete("", error: true)]
        public const string RemoveEmptyLineBetweenUsingDirectivesWithDifferentRootNamespace2 = "RCS0037";
    }
}