// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

namespace Roslynator.CodeStyle
{
    internal static partial class CodeStyleDescriptors
    {
        public static readonly CodeStyleDescriptor UseElementAccessOnInvocation = new CodeStyleDescriptor(
            id: CodeStyleIdentifiers.UseElementAccessOnInvocation,
            isEnabledByDefault: true,
            summary: null);
    }
}
