// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

namespace Roslynator.CodeStyle
{
    internal static partial class CodeStyleIdentifiers
    {
        public const string ParenthesizeSimpleConditionOfConditionalExpression = Prefix + nameof(ParenthesizeSimpleConditionOfConditionalExpression);
        public const string UseElementAccessOnElementAccess = Prefix + nameof(UseElementAccessOnElementAccess);
        public const string UseElementAccessOnInvocation = Prefix + nameof(UseElementAccessOnInvocation);
    }
}
