// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

namespace Roslynator.CodeStyle
{
    internal static partial class CodeStyleDescriptors
    {
        public static readonly CodeStyleDescriptor ParenthesizeSimpleConditionOfConditionalExpression = new CodeStyleDescriptor(
            id:                 CodeStyleIdentifiers.ParenthesizeSimpleConditionOfConditionalExpression, 
            title:              "Parenthesize simple condition of conditional expression", 
            isEnabledByDefault: true, 
            summary:            "");

        public static readonly CodeStyleDescriptor UseElementAccessOnElementAccess = new CodeStyleDescriptor(
            id:                 CodeStyleIdentifiers.UseElementAccessOnElementAccess, 
            title:              "Use element access on element access", 
            isEnabledByDefault: true, 
            summary:            "");

        public static readonly CodeStyleDescriptor UseElementAccessOnInvocation = new CodeStyleDescriptor(
            id:                 CodeStyleIdentifiers.UseElementAccessOnInvocation, 
            title:              "Use element access on invocation", 
            isEnabledByDefault: true, 
            summary:            "");

    }
}