// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

namespace Roslynator.Options
{
    internal static partial class AnalyzerOptionDescriptors
    {
        public static readonly AnalyzerOptionDescriptor ParenthesizeSimpleConditionOfConditionalExpression = new AnalyzerOptionDescriptor(
            id:                 AnalyzerOptionIdentifiers.ParenthesizeSimpleConditionOfConditionalExpression, 
            title:              "Parenthesize simple condition of conditional expression", 
            isEnabledByDefault: true, 
            summary:            "");

        public static readonly AnalyzerOptionDescriptor UseElementAccessOnElementAccess = new AnalyzerOptionDescriptor(
            id:                 AnalyzerOptionIdentifiers.UseElementAccessOnElementAccess, 
            title:              "Use element access on element access", 
            isEnabledByDefault: true, 
            summary:            "");

        public static readonly AnalyzerOptionDescriptor UseElementAccessOnInvocation = new AnalyzerOptionDescriptor(
            id:                 AnalyzerOptionIdentifiers.UseElementAccessOnInvocation, 
            title:              "Use element access on invocation", 
            isEnabledByDefault: true, 
            summary:            "");

    }
}