// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

namespace Roslynator.Options
{
    internal static partial class AnalyzerOptionIdentifiers
    {
        public const string ParenthesizeSimpleConditionOfConditionalExpression = "Roslynator.ParenthesizeSimpleConditionOfConditionalExpression";
        public const string UseElementAccessOnElementAccess = "Roslynator.UseElementAccessOnElementAccess";
        public const string UseElementAccessOnInvocation = "Roslynator.UseElementAccessOnInvocation";
    }
}